### ISSUE TITLE
could not build Objective-C module 'libxml2'

### ISSUE THREAD

**Issue by jigarviprak** [tid-kijyun/Kanna#122] opened 2016-11-26 11:16 UTC
### Description:
error: 'libxml/xmlversion.h' file not found

could not build Objective-C module 'libxml2'

my current xcode version 8.1
and also using swift 3.0

### Installation method:
- [ ] Carthage
- [x] CocoaPods(1.1.0 or later)
- [ ] CocoaPods(older)
- [ ] Manually

### Library version:
- [x] v2.0.0
- [ ] v1.1.1
- [ ] v1.0.6
- [ ] v1.0.2
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 (Swift 3.0) 
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

**Comment by tid-kijyun** [comment] 2016-12-05 18:05
Please try v2.1.0.

```
pod 'Kanna', '~> 2.1.0'
```

**Comment by wmcbain** [comment] 2016-12-14 03:01
**Description**

I'm seeing a dupe of this error with `2.1.1` using the Swift Package Manager and using `swift build`.

[Output](https://gist.github.com/wmcbain/67f86f940dba79fd916601a92adf9d93)

**Installation method:**

Swift package manager.

**Library version:**

 v2.1.1

Xcode version:

 8.0 (Swift 3.0)

**Closed** 2016-12-14 09:16 UTC
