### ISSUE TITLE
'libxml/xmlversion.h' file not found

### ISSUE THREAD

**Issue by gschafer** [tid-kijyun/Kanna#144] opened 2017-04-11 18:32 UTC
### Description:
I've solved my issue already, but I'm posting my solution in case someone is experiencing the same problem. 

After updating version from 2.0.0 to 2.2.1 the following error started happening
'libxml/xmlversion.h' file not found
Could not build Objective-C module 'libxml2'

Right now I'm using Kanna on my private lib that loads it from .podspec file

I was able to replicate my solution by adding:
s.xcconfig      = {
          'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2',
          'SWIFT_INCLUDE_PATHS' => '$(SRCROOT)/Kanna/Modules'
  }

to my .podspec right above:
s.dependency 'Kanna', '~> 2.2.1'

That narrowed the error down to the  "Project name"_Tests target and I've noticed that some people mentioned about adding "$(SDKROOT)/usr/include/libxml2" to the header search paths, my <Project name> target already had that path, but the "Project name"_Tests target didn't, once I've added the the search path to the "Project name"_Tests, cleaned the project, crossed my fingers and finally hit pod update.

It cleared the error for me, hopefully it will help someone else 

PS. I don't know all the in and outs of cocoapods, neither Kanna, and I have no idea what I did, but I was able to replicate the solution a few times, feel free to explain or tell me why/how I'm wrong

### Installation method:
- [ ] Carthage
- [x] CocoaPods(1.1.0 or later)
- [ ] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Library version:
- [x] v2.1.1
- [ ] other: ()

### Xcode version:
- [x] 8.1 (Swift 3) 
- [ ] 8.1 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: ()

**Comment by ikajava** [comment] 2017-04-19 22:07
Maybe it's a stupid question, but what's a "_Tests target"?

**Comment by gschafer** [comment] 2017-04-19 23:55
@ikajava not stupid at all, I should have made it clearer, when you create a library using the pod lib create command the example project usually contains 2 targets "Project name"_Example and "Project name"_Tests. Where "Project name"_Tests target was giving me the ''libxml/xmlversion.h' file not found' error, adding "$(SDKROOT)/usr/include/libxml2" to "HEADER_SEARCH_PATHS" to it's Built Settings solved the issue for me.

**Comment by proth** [comment] 2017-07-23 20:16
This issue seems to be the same as this one:
https://github.com/tid-kijyun/Kanna/issues/140

**Comment by proth** [comment] 2017-07-23 21:13
I use Kanna as a dependency on a pod I am developing.
Here is what fixed the issue for me:
`s.pod_target_xcconfig = { 'HEADER_SEARCH_PATHS' => "$(SDKROOT)/usr/include/libxml2" }`
Adding this line to your podspec fixed the issue under mac OS 10.10+

```
Pod::Spec.new do |s|
  s.name         = "MyPod"
...
  s.source       = { :git => "...", :tag => "..." }

  s.pod_target_xcconfig = { 'HEADER_SEARCH_PATHS' => "$(SDKROOT)/usr/include/libxml2" }

  s.osx.deployment_target = "10.12"

  s.source_files  = "..."

  s.requires_arc = true

  s.dependency "Kanna"
end
```

**Comment by georgealegre** [comment] 2017-09-22 10:54
I solved this by removing the dependency and adding it again.

**Comment by kevin** [comment] 2019-05-05 22:28
Okay guys so I have a fix for this for the ["Swift Package Manager"](https://swift.org/package-manager/) build system. I know this system doesn't seem to be too popular among most developers, but I'm coming from python and I absolutely LOVE IT.  On the other hand all the magic and voodoo going on with the other two options .... is something that is a big turn off for me.

A lot developers seem to have COMPLETELY neglected their package.json files leaving them in 1.0 or 2.0 format despite moving ahead with support for Swift 4.2 and 5 in Xcode.

The main problem with the SPM right now isn't really with anything _wrong_ or _missing_ with its actual build or API systems, but the documentation is super fragmented.  There's one set of docs on swift.org that is ABYSMAL .... and another at their git which isn't too bad.  They need to either update the swift.org docs or **at least** provide a PROMINENT link to the full set of documentation that's available at their git!

I actually didn't find the docs at the git until after I did this the hard way and went looking through Apple's own internal swift libraries to see how they were linking to C dependencies.  Basically, you make a little wrapper with no code other than package.json and a modulemap which describes the headers.

*HERE* is the documentation!   https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#require-system-libraries

My libxml wrapper I'm using right now, and will be making an attempt to integrate into Kanna's SPM build system today .... is basically just a cut/paste of Apple's libxml2 from their internal stuff inside their jumble of Xcode nonsense.  There may be no need to actually post these little wrappers on GitHub, since they all exist inside Apple's jumble of build systems and Xcode hackery.

Also, someone smarter than me needs to write a little library that builds these module-maps ... or better yet apple needs to include the functionality in SPM because it *definitely* could be automated (maybe it already is and I missed that in the docs :).

So this isn't a fix for Carthage, or Pod what-ever, but it is a fix for libxml if you're building with SPM.  Trust me once you have all the SPM stuff up to date and understand how it's supposed to work, it's a dream compared to carthage and pods.

Problem is of course this *extreme* neglect that is pretty pervasive across all the public libraries when it comes to package.json.  Half the libraries haven't updated it since they first tried it out at version 1 or 2.

I'm going to start by uploading to GitHub (and probably gitlab since that's my main squeeze) the libxml wrapper.  You include it in your package.json just like any other dependency and bob's your uncle.

Next thing I'm going to do is branch every library I'm using in my project and fix the SPM build system.  That likely includes Kanna.... I can send pull requests back your way... but I'm going to be doing some crazy stuff like wiping out your entire set of version tags since SPM doesn't seem to like it when there is this crazy mish-mash of version styles.  So I'll retag everything as best I can, but with a focus on the more recent versions.  In the end though, you may want to do this your own way and just use my code as a guide or what-have-you.

Sorry for the long reply, but hopefully this information Is useful for you guys.

I'd really like for the community to get onto this whole SPM bandwagon.  Despite the jumbled up hard to find documentation the code itself is in a fantastic state ... and is ready for PRIME TIME (I'm a bit new to swift, so I understand there may be some negative sentiments towards previous SPM versions that are probably WELL deserved, but the latest is really the greatest of all the build systems out there).

To ramble on a bit more.  My basic process consists of getting all the nuts and bolts of my app working WITHOUT Xcode.  Then once the nuts and bolts of the library are building, testing, and running smooth as budder ... I use the SPM command to create an Xcode project file and we're off to the races building the GUI.

For libraries like this that consist solely of backend/non-user-interface code there really is no need for Xcode involvement in the first place.  KISS!  This could easily be a cross-platform library if we dropped the Xcode and Carthage and PodRacer (much better name) or what-ever it's called and stuck to the cross-platform SPM system.   IT"S THE FUTURE!!!

Again sorry for the long rambling nonsense, but hopefully you guys get the gist of what I'm trying to say here.... and hopefully you're excited about cross-platform support and the distance from Xcode that SPM provides :)

I've tested this with other libraries suffering the same issues with libxml2 (AND IT WORKED!!!!), but haven't integrated it into Kanna quite yet (I'll be starting by fixing Erik and all of its dependencies, which includes Kanna).  So today I'm going to try and integrate my little libxml wrapper into Kanna's SPM build system, get the versioning working... and so on.  Hopefully by end of day you'll see not just the stupid libxml2 wrapper I made, but it actually WORKING in a Kanna-SPM-4.2+ branch.

I'm real excited about getting _working_ support for SPM into as many libraries as I can.   So hopefully, my little contribution here can help spread the understanding that SPM is AWESOME and ready to take over for the other libraries out there and getting you guys off of these magical build systems like Carthage and CocoaPuffs (Again, MUCH better name) that are MacOS specific.

-k. noah

**Comment by chromakey-io** [comment] 2019-05-17 10:54
1) the fix for this is with home-brew.  the .pc file isn't linked and their build .rb has a broken system that seems like it's attempting to find what-ever is appropriate for your version of OSX (a separate .pc for each) ... but fails rather spectacularly.

2) To fix this error,  1) make sure pig-config is installed with home-brew 2) make sure you have a libxml-2.0.pc file in /usr/local/lib/pkgconfig/ ... either symlink one of the 10 versions home-brew generates based on your OS version ... or just link the file in the Cellar :)


Go ahead and ignore my previous post, and long ramble about SPM, etc.   Not only are you guys up to date with a working 5.0 SPM Package.swift, but you're using the new "Target" system which doesn't even have real documentation published yet.

Now I'm going up the tree of the other libraries I'm using and the main offender seems to be the biggest library I have to depend on ... "Erik".  He has a custom path for his sources, 2 or 3 custom Test targets all at random paths ... and has just all around ignored the specs, etc ... and the Package.swift isn't even version (which I guess means it's what? 1.0?).  The library seems spectacular if I can actually get it to build, but holy geese.

Regardless sorry for the ramble, you guys seem to be doing a great job with SPM.  Continue, though there seem to be a lot of people with this same issue, so maybe some instructions about the missing .pc file from home-brew (it gives instructions itself to put it in the PKG_CONFIG_PATH, but that's kind of silly imo when you can. just properly link the file into /usr/local/lib/pkgconfig.

What I really want to know though is what about building agains the libxml2's sitting in each of xCode's build trees for each Target? iOS, TV, etc.  It seems like maybe there's a way to do this with the new target system, but I need to play around with it a bit more ..

Once again sry for the long-ish post.

**Comment by tid-kijyun** [comment] 2020-03-28 13:46
Closed because it is a problem in the old version.
Feel free to repost if the issue is not resolved.

**Closed by tid-kijyun** 2020-03-28 13:46 UTC
